// Superhero powers array
const powers = [
    'Super Strength',
    'Invisibility',
    'Flight',
    'Telepathy',
    'Super Speed',
    'Time Travel',
    'Shape Shifting',
    'Energy Manipulation',
    'Teleportation',
    'Invulnerability',
    'Healing',
    'Mind Reading',
    'Weather Control',
    'Magnetism',
    'Telekinesis',
    'X-ray Vision',
    'Laser Eyes',
    'Super Agility',
    'Immortality',
    'Wall Crawling',
    'Animal Communication',
    'Force Field Creation',
    'Reality Warping',
    'Dream Manipulation',
    'Clairvoyance',
    'Size Alteration',
    'Duplication',
    'Elasticity',
    'Super Intelligence',
    'Technomancy',
    'Teleportation Through Time',
    'Super Reflexes',
    'Sound Manipulation',
    'Fire Manipulation',
    'Water Manipulation',
    'Earth Manipulation',
    'Ice Manipulation',
    'Plant Control',
    'Light Manipulation',
    'Darkness Manipulation',
    'Gravity Control',
    'Precognition',
    'Regeneration',
    'Dimensional Travel',
    'Super Memory',
    'Super Hearing',
    'Super Vision',
    'Empathy',
    'Mind Control',
    'Illusion Creation',
    'Super Stamina',
    'Invincibility',
    'Energy Absorption',
    'Pheromone Control',
    'Shapeshifting Into Animals',
    'Underwater Breathing',
    'Intangibility',
    'Weather Prediction',
    'Super Breath',
    'Electricity Manipulation',
    'Mind Projection',
    'Enhanced Senses',
    'Super Hacking',
    'Time Manipulation',
    'Super Charisma',
    'Super Luck',
    'Psychometry',
    'Rewind Time',
    'Size Control',
    'Wind Manipulation',
    'Pyrokinesis (Fire Power)',
    'Hydrokinesis (Water Power)',
    'Geokinesis (Earth Power)',
    'Chronokinesis (Time Power)',
    'Teleportation by Sneezing',
    'Reverse Aging',
    'Super Texting Speed',
    'Pizza Summoning',
    'Hyper Jumping',
    'Super Tasting',
    'Ability to Speak All Languages',
    'Super Cooking Skills',
    'Magical Animal Communication',
    'Wi-Fi Control',
    'Ability to Summon Ghosts',
    'Unstoppable Dance Moves',
    'You Can Turn Invisible by Holding Your Breath',
    'Super Snoring',
    'Super Spelling Bee Champion',
    'Super Procrastination',
    'Ability to Summon Snack Foods',
    'Super Comic Book Knowledge',
    'Ability to Talk to Your Plants',
    'Shapeshift Into Your Favorite Celebrity',
    'Turning Into a Puddle of Jelly',
    'Ability to Make People Laugh with One Word',
    'Super Ability to Nap Anywhere',
    'Unlimited Internet Streaming Power',
    'Coffee Summoning',
    'Super Finger Snap',
    'Laser Tag Champion',
    'Super Absurd Fashion Sense',
    'Ability to Turn into a Blob of Gelatin',
    'Super Ability to Find Lost Socks',
    'Super Power of Teleporting to the Kitchen',
    'Unlimited High Fives',
    'Ability to Breakdance at Will',
    'Laughing So Hard You Cry',
    'Teleportation Through Your Cat',
    'Super Endurance to Watch Every Episode of a Show',
    'The Ability to Speak Fluent Emoji',
    'Super Nap-Taking Powers',
    'Super Ability to Guess Movie Plots',
    'Can Summon Popcorn at Will',
    'Can Communicate with Your Wi-Fi Router',
    'Super Ability to Find Hidden Easter Eggs in Games',
    'Super Sneeze',
    'Can Turn Into a Potato at Will',
    'T-shirt Printing Superpower',
    'Ultimate Social Media Influence',
    'The Ability to Summon Ice Cream Cones',
    'Waking Up with No Alarm Clock Power',
    'Super Instant Pizza Making',
    'Super Sneezing Powers',
    'Never Getting Lost Power',
    'The Ability to Win Every Argument',
    'The Ability to Summon Bubbles',
    'Meme Generation Power',
    'The Ability to Charm Your Phone’s Battery',
    'Super Ability to Get Free Wi-Fi',
    'Super Ability to Find the Perfect Seat at a Concert',
    'Super Speed Texting',
    'Power of Never Burning Toast',
    'The Ability to Speak Fluent Animal',
    'Unstoppable Karaoke Talent',
    'Super Ability to Find the Perfect Streaming Show',
    'Super Sleep Talking Powers'
];

// Function to generate a random power
function generatePower() {
    const randomIndex = Math.floor(Math.random() * powers.length);
    const power = powers[randomIndex];

    const powerMessage = `Your superpower is <br><span id="superPowerText">${power}</span>.`;
    document.getElementById('powerDisplay').innerHTML = powerMessage; // Insert the message

}

// Event listener for the button
document.getElementById('generateButton').addEventListener('click', generatePower);
